# Generated by Django 3.0.4 on 2020-03-28 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200328_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='image',
            new_name='image123',
        ),
    ]
