# Generated by Django 3.0.4 on 2020-03-28 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200328_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='image123',
            new_name='image',
        ),
    ]
