# Generated by Django 3.0.4 on 2020-03-28 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blob',
            new_name='Blog',
        ),
    ]
